### PR TITLE
Appender Rename Fixes

### LINKED ISSUE #38: Renaming an Appender Does Not Remove/Rename Old Appender Ref
If an appender is renamed its corresponding `appender-ref` is not. This generates the following error:
```
log4net:ERROR XmlHierarchyConfigurator: No appender named [missing] could be found.
log4net:ERROR Appender named [missing] not found.
```
Where "missing" is the old name. The new name is still saved in the desired ref location(s), however, meaning the appender will continue to work.

### PR DESCRIPTION
**Pull request by alexleen**
Resolves #38

### CODE REVIEW

File: Source/Editor/Utilities/XmlUtilities.cs [hunk 1]
```diff
@@ -68,6 +68,14 @@ private static IEnumerable<LoggerModel> CreateLoggerModelsFromNodes(XmlNode log4
             }
         }
 
+        /// <summary>
+        /// Adds the specified <paramref name="appenderName"/> to the specified <paramref name="node"/> as an appender-ref.
```
Comment (alexleen) [inline Source/Editor/Utilities/XmlUtilities.cs]: ... as an appender-ref child.
